# Generated by Django 5.1.6 on 2025-03-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('HR', 'HR'), ('Manager', 'Менеджер'), ('Accountant', 'Бухгалтер'), ('Employee', 'Обычный работник'), ('Admin', 'Админ')], default='Employee', max_length=20),
        ),
    ]
