# Generated by Django 5.1.6 on 2025-03-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Temporary', 'Temporary')], default='Full-time', max_length=50),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
