# Generated by Django 5.1.6 on 2025-03-17 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_contract_contract_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_position', models.CharField(max_length=50)),
                ('new_position', models.CharField(max_length=50)),
                ('changed_at', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_history', to='employees.employee')),
            ],
        ),
    ]
