# Generated by Django 5.1.6 on 2025-03-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_positionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='overtime_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
