# Generated by Django 5.1.6 on 2025-03-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_overtime_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='overtime_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salary',
            name='unpaid_leave_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salary',
            name='total_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
