# Generated by Django 5.1.6 on 2025-03-19 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_training_employeetraining'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='employees',
            field=models.ManyToManyField(related_name='enrolled_trainings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeetraining',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='training',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='employeetraining',
            unique_together={('employee', 'training')},
        ),
    ]
