# Generated by Django 5.1.6 on 2025-03-19 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_training_employees_alter_employeetraining_employee_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeetraining',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='training',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='training',
            name='is_mandatory',
        ),
        migrations.AlterField(
            model_name='employeetraining',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeetraining',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='employeetraining',
            name='status',
            field=models.CharField(choices=[('assigned', 'Назначен'), ('completed', 'Завершён')], default='assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeetraining',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.training'),
        ),
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
